package com.echarts.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ComPanyDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table companydetail
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table companydetail
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table companydetail
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companydetail
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public ComPanyDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companydetail
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companydetail
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companydetail
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companydetail
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companydetail
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companydetail
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companydetail
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companydetail
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companydetail
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companydetail
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table companydetail
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andCompanynameIsNull() {
            addCriterion("companyName is null");
            return (Criteria) this;
        }

        public Criteria andCompanynameIsNotNull() {
            addCriterion("companyName is not null");
            return (Criteria) this;
        }

        public Criteria andCompanynameEqualTo(String value) {
            addCriterion("companyName =", value, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameNotEqualTo(String value) {
            addCriterion("companyName <>", value, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameGreaterThan(String value) {
            addCriterion("companyName >", value, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameGreaterThanOrEqualTo(String value) {
            addCriterion("companyName >=", value, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameLessThan(String value) {
            addCriterion("companyName <", value, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameLessThanOrEqualTo(String value) {
            addCriterion("companyName <=", value, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameLike(String value) {
            addCriterion("companyName like", value, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameNotLike(String value) {
            addCriterion("companyName not like", value, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameIn(List<String> values) {
            addCriterion("companyName in", values, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameNotIn(List<String> values) {
            addCriterion("companyName not in", values, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameBetween(String value1, String value2) {
            addCriterion("companyName between", value1, value2, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameNotBetween(String value1, String value2) {
            addCriterion("companyName not between", value1, value2, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanylicenceIsNull() {
            addCriterion("companyLicence is null");
            return (Criteria) this;
        }

        public Criteria andCompanylicenceIsNotNull() {
            addCriterion("companyLicence is not null");
            return (Criteria) this;
        }

        public Criteria andCompanylicenceEqualTo(String value) {
            addCriterion("companyLicence =", value, "companylicence");
            return (Criteria) this;
        }

        public Criteria andCompanylicenceNotEqualTo(String value) {
            addCriterion("companyLicence <>", value, "companylicence");
            return (Criteria) this;
        }

        public Criteria andCompanylicenceGreaterThan(String value) {
            addCriterion("companyLicence >", value, "companylicence");
            return (Criteria) this;
        }

        public Criteria andCompanylicenceGreaterThanOrEqualTo(String value) {
            addCriterion("companyLicence >=", value, "companylicence");
            return (Criteria) this;
        }

        public Criteria andCompanylicenceLessThan(String value) {
            addCriterion("companyLicence <", value, "companylicence");
            return (Criteria) this;
        }

        public Criteria andCompanylicenceLessThanOrEqualTo(String value) {
            addCriterion("companyLicence <=", value, "companylicence");
            return (Criteria) this;
        }

        public Criteria andCompanylicenceLike(String value) {
            addCriterion("companyLicence like", value, "companylicence");
            return (Criteria) this;
        }

        public Criteria andCompanylicenceNotLike(String value) {
            addCriterion("companyLicence not like", value, "companylicence");
            return (Criteria) this;
        }

        public Criteria andCompanylicenceIn(List<String> values) {
            addCriterion("companyLicence in", values, "companylicence");
            return (Criteria) this;
        }

        public Criteria andCompanylicenceNotIn(List<String> values) {
            addCriterion("companyLicence not in", values, "companylicence");
            return (Criteria) this;
        }

        public Criteria andCompanylicenceBetween(String value1, String value2) {
            addCriterion("companyLicence between", value1, value2, "companylicence");
            return (Criteria) this;
        }

        public Criteria andCompanylicenceNotBetween(String value1, String value2) {
            addCriterion("companyLicence not between", value1, value2, "companylicence");
            return (Criteria) this;
        }

        public Criteria andRegistrarnameIsNull() {
            addCriterion("registrarName is null");
            return (Criteria) this;
        }

        public Criteria andRegistrarnameIsNotNull() {
            addCriterion("registrarName is not null");
            return (Criteria) this;
        }

        public Criteria andRegistrarnameEqualTo(String value) {
            addCriterion("registrarName =", value, "registrarname");
            return (Criteria) this;
        }

        public Criteria andRegistrarnameNotEqualTo(String value) {
            addCriterion("registrarName <>", value, "registrarname");
            return (Criteria) this;
        }

        public Criteria andRegistrarnameGreaterThan(String value) {
            addCriterion("registrarName >", value, "registrarname");
            return (Criteria) this;
        }

        public Criteria andRegistrarnameGreaterThanOrEqualTo(String value) {
            addCriterion("registrarName >=", value, "registrarname");
            return (Criteria) this;
        }

        public Criteria andRegistrarnameLessThan(String value) {
            addCriterion("registrarName <", value, "registrarname");
            return (Criteria) this;
        }

        public Criteria andRegistrarnameLessThanOrEqualTo(String value) {
            addCriterion("registrarName <=", value, "registrarname");
            return (Criteria) this;
        }

        public Criteria andRegistrarnameLike(String value) {
            addCriterion("registrarName like", value, "registrarname");
            return (Criteria) this;
        }

        public Criteria andRegistrarnameNotLike(String value) {
            addCriterion("registrarName not like", value, "registrarname");
            return (Criteria) this;
        }

        public Criteria andRegistrarnameIn(List<String> values) {
            addCriterion("registrarName in", values, "registrarname");
            return (Criteria) this;
        }

        public Criteria andRegistrarnameNotIn(List<String> values) {
            addCriterion("registrarName not in", values, "registrarname");
            return (Criteria) this;
        }

        public Criteria andRegistrarnameBetween(String value1, String value2) {
            addCriterion("registrarName between", value1, value2, "registrarname");
            return (Criteria) this;
        }

        public Criteria andRegistrarnameNotBetween(String value1, String value2) {
            addCriterion("registrarName not between", value1, value2, "registrarname");
            return (Criteria) this;
        }

        public Criteria andRegistrarphoneIsNull() {
            addCriterion("registrarPhone is null");
            return (Criteria) this;
        }

        public Criteria andRegistrarphoneIsNotNull() {
            addCriterion("registrarPhone is not null");
            return (Criteria) this;
        }

        public Criteria andRegistrarphoneEqualTo(String value) {
            addCriterion("registrarPhone =", value, "registrarphone");
            return (Criteria) this;
        }

        public Criteria andRegistrarphoneNotEqualTo(String value) {
            addCriterion("registrarPhone <>", value, "registrarphone");
            return (Criteria) this;
        }

        public Criteria andRegistrarphoneGreaterThan(String value) {
            addCriterion("registrarPhone >", value, "registrarphone");
            return (Criteria) this;
        }

        public Criteria andRegistrarphoneGreaterThanOrEqualTo(String value) {
            addCriterion("registrarPhone >=", value, "registrarphone");
            return (Criteria) this;
        }

        public Criteria andRegistrarphoneLessThan(String value) {
            addCriterion("registrarPhone <", value, "registrarphone");
            return (Criteria) this;
        }

        public Criteria andRegistrarphoneLessThanOrEqualTo(String value) {
            addCriterion("registrarPhone <=", value, "registrarphone");
            return (Criteria) this;
        }

        public Criteria andRegistrarphoneLike(String value) {
            addCriterion("registrarPhone like", value, "registrarphone");
            return (Criteria) this;
        }

        public Criteria andRegistrarphoneNotLike(String value) {
            addCriterion("registrarPhone not like", value, "registrarphone");
            return (Criteria) this;
        }

        public Criteria andRegistrarphoneIn(List<String> values) {
            addCriterion("registrarPhone in", values, "registrarphone");
            return (Criteria) this;
        }

        public Criteria andRegistrarphoneNotIn(List<String> values) {
            addCriterion("registrarPhone not in", values, "registrarphone");
            return (Criteria) this;
        }

        public Criteria andRegistrarphoneBetween(String value1, String value2) {
            addCriterion("registrarPhone between", value1, value2, "registrarphone");
            return (Criteria) this;
        }

        public Criteria andRegistrarphoneNotBetween(String value1, String value2) {
            addCriterion("registrarPhone not between", value1, value2, "registrarphone");
            return (Criteria) this;
        }

        public Criteria andIncorporatornameIsNull() {
            addCriterion("incorporatorName is null");
            return (Criteria) this;
        }

        public Criteria andIncorporatornameIsNotNull() {
            addCriterion("incorporatorName is not null");
            return (Criteria) this;
        }

        public Criteria andIncorporatornameEqualTo(String value) {
            addCriterion("incorporatorName =", value, "incorporatorname");
            return (Criteria) this;
        }

        public Criteria andIncorporatornameNotEqualTo(String value) {
            addCriterion("incorporatorName <>", value, "incorporatorname");
            return (Criteria) this;
        }

        public Criteria andIncorporatornameGreaterThan(String value) {
            addCriterion("incorporatorName >", value, "incorporatorname");
            return (Criteria) this;
        }

        public Criteria andIncorporatornameGreaterThanOrEqualTo(String value) {
            addCriterion("incorporatorName >=", value, "incorporatorname");
            return (Criteria) this;
        }

        public Criteria andIncorporatornameLessThan(String value) {
            addCriterion("incorporatorName <", value, "incorporatorname");
            return (Criteria) this;
        }

        public Criteria andIncorporatornameLessThanOrEqualTo(String value) {
            addCriterion("incorporatorName <=", value, "incorporatorname");
            return (Criteria) this;
        }

        public Criteria andIncorporatornameLike(String value) {
            addCriterion("incorporatorName like", value, "incorporatorname");
            return (Criteria) this;
        }

        public Criteria andIncorporatornameNotLike(String value) {
            addCriterion("incorporatorName not like", value, "incorporatorname");
            return (Criteria) this;
        }

        public Criteria andIncorporatornameIn(List<String> values) {
            addCriterion("incorporatorName in", values, "incorporatorname");
            return (Criteria) this;
        }

        public Criteria andIncorporatornameNotIn(List<String> values) {
            addCriterion("incorporatorName not in", values, "incorporatorname");
            return (Criteria) this;
        }

        public Criteria andIncorporatornameBetween(String value1, String value2) {
            addCriterion("incorporatorName between", value1, value2, "incorporatorname");
            return (Criteria) this;
        }

        public Criteria andIncorporatornameNotBetween(String value1, String value2) {
            addCriterion("incorporatorName not between", value1, value2, "incorporatorname");
            return (Criteria) this;
        }

        public Criteria andCompanystateIsNull() {
            addCriterion("companyState is null");
            return (Criteria) this;
        }

        public Criteria andCompanystateIsNotNull() {
            addCriterion("companyState is not null");
            return (Criteria) this;
        }

        public Criteria andCompanystateEqualTo(Byte value) {
            addCriterion("companyState =", value, "companystate");
            return (Criteria) this;
        }

        public Criteria andCompanystateNotEqualTo(Byte value) {
            addCriterion("companyState <>", value, "companystate");
            return (Criteria) this;
        }

        public Criteria andCompanystateGreaterThan(Byte value) {
            addCriterion("companyState >", value, "companystate");
            return (Criteria) this;
        }

        public Criteria andCompanystateGreaterThanOrEqualTo(Byte value) {
            addCriterion("companyState >=", value, "companystate");
            return (Criteria) this;
        }

        public Criteria andCompanystateLessThan(Byte value) {
            addCriterion("companyState <", value, "companystate");
            return (Criteria) this;
        }

        public Criteria andCompanystateLessThanOrEqualTo(Byte value) {
            addCriterion("companyState <=", value, "companystate");
            return (Criteria) this;
        }

        public Criteria andCompanystateIn(List<Byte> values) {
            addCriterion("companyState in", values, "companystate");
            return (Criteria) this;
        }

        public Criteria andCompanystateNotIn(List<Byte> values) {
            addCriterion("companyState not in", values, "companystate");
            return (Criteria) this;
        }

        public Criteria andCompanystateBetween(Byte value1, Byte value2) {
            addCriterion("companyState between", value1, value2, "companystate");
            return (Criteria) this;
        }

        public Criteria andCompanystateNotBetween(Byte value1, Byte value2) {
            addCriterion("companyState not between", value1, value2, "companystate");
            return (Criteria) this;
        }

        public Criteria andAudittimeIsNull() {
            addCriterion("auditTime is null");
            return (Criteria) this;
        }

        public Criteria andAudittimeIsNotNull() {
            addCriterion("auditTime is not null");
            return (Criteria) this;
        }

        public Criteria andAudittimeEqualTo(Date value) {
            addCriterion("auditTime =", value, "audittime");
            return (Criteria) this;
        }

        public Criteria andAudittimeNotEqualTo(Date value) {
            addCriterion("auditTime <>", value, "audittime");
            return (Criteria) this;
        }

        public Criteria andAudittimeGreaterThan(Date value) {
            addCriterion("auditTime >", value, "audittime");
            return (Criteria) this;
        }

        public Criteria andAudittimeGreaterThanOrEqualTo(Date value) {
            addCriterion("auditTime >=", value, "audittime");
            return (Criteria) this;
        }

        public Criteria andAudittimeLessThan(Date value) {
            addCriterion("auditTime <", value, "audittime");
            return (Criteria) this;
        }

        public Criteria andAudittimeLessThanOrEqualTo(Date value) {
            addCriterion("auditTime <=", value, "audittime");
            return (Criteria) this;
        }

        public Criteria andAudittimeIn(List<Date> values) {
            addCriterion("auditTime in", values, "audittime");
            return (Criteria) this;
        }

        public Criteria andAudittimeNotIn(List<Date> values) {
            addCriterion("auditTime not in", values, "audittime");
            return (Criteria) this;
        }

        public Criteria andAudittimeBetween(Date value1, Date value2) {
            addCriterion("auditTime between", value1, value2, "audittime");
            return (Criteria) this;
        }

        public Criteria andAudittimeNotBetween(Date value1, Date value2) {
            addCriterion("auditTime not between", value1, value2, "audittime");
            return (Criteria) this;
        }

        public Criteria andRegistertimeIsNull() {
            addCriterion("registerTime is null");
            return (Criteria) this;
        }

        public Criteria andRegistertimeIsNotNull() {
            addCriterion("registerTime is not null");
            return (Criteria) this;
        }

        public Criteria andRegistertimeEqualTo(Date value) {
            addCriterion("registerTime =", value, "registertime");
            return (Criteria) this;
        }

        public Criteria andRegistertimeNotEqualTo(Date value) {
            addCriterion("registerTime <>", value, "registertime");
            return (Criteria) this;
        }

        public Criteria andRegistertimeGreaterThan(Date value) {
            addCriterion("registerTime >", value, "registertime");
            return (Criteria) this;
        }

        public Criteria andRegistertimeGreaterThanOrEqualTo(Date value) {
            addCriterion("registerTime >=", value, "registertime");
            return (Criteria) this;
        }

        public Criteria andRegistertimeLessThan(Date value) {
            addCriterion("registerTime <", value, "registertime");
            return (Criteria) this;
        }

        public Criteria andRegistertimeLessThanOrEqualTo(Date value) {
            addCriterion("registerTime <=", value, "registertime");
            return (Criteria) this;
        }

        public Criteria andRegistertimeIn(List<Date> values) {
            addCriterion("registerTime in", values, "registertime");
            return (Criteria) this;
        }

        public Criteria andRegistertimeNotIn(List<Date> values) {
            addCriterion("registerTime not in", values, "registertime");
            return (Criteria) this;
        }

        public Criteria andRegistertimeBetween(Date value1, Date value2) {
            addCriterion("registerTime between", value1, value2, "registertime");
            return (Criteria) this;
        }

        public Criteria andRegistertimeNotBetween(Date value1, Date value2) {
            addCriterion("registerTime not between", value1, value2, "registertime");
            return (Criteria) this;
        }

        public Criteria andLoanstateIsNull() {
            addCriterion("loanState is null");
            return (Criteria) this;
        }

        public Criteria andLoanstateIsNotNull() {
            addCriterion("loanState is not null");
            return (Criteria) this;
        }

        public Criteria andLoanstateEqualTo(Byte value) {
            addCriterion("loanState =", value, "loanstate");
            return (Criteria) this;
        }

        public Criteria andLoanstateNotEqualTo(Byte value) {
            addCriterion("loanState <>", value, "loanstate");
            return (Criteria) this;
        }

        public Criteria andLoanstateGreaterThan(Byte value) {
            addCriterion("loanState >", value, "loanstate");
            return (Criteria) this;
        }

        public Criteria andLoanstateGreaterThanOrEqualTo(Byte value) {
            addCriterion("loanState >=", value, "loanstate");
            return (Criteria) this;
        }

        public Criteria andLoanstateLessThan(Byte value) {
            addCriterion("loanState <", value, "loanstate");
            return (Criteria) this;
        }

        public Criteria andLoanstateLessThanOrEqualTo(Byte value) {
            addCriterion("loanState <=", value, "loanstate");
            return (Criteria) this;
        }

        public Criteria andLoanstateIn(List<Byte> values) {
            addCriterion("loanState in", values, "loanstate");
            return (Criteria) this;
        }

        public Criteria andLoanstateNotIn(List<Byte> values) {
            addCriterion("loanState not in", values, "loanstate");
            return (Criteria) this;
        }

        public Criteria andLoanstateBetween(Byte value1, Byte value2) {
            addCriterion("loanState between", value1, value2, "loanstate");
            return (Criteria) this;
        }

        public Criteria andLoanstateNotBetween(Byte value1, Byte value2) {
            addCriterion("loanState not between", value1, value2, "loanstate");
            return (Criteria) this;
        }

        public Criteria andCompanytypeIsNull() {
            addCriterion("companyType is null");
            return (Criteria) this;
        }

        public Criteria andCompanytypeIsNotNull() {
            addCriterion("companyType is not null");
            return (Criteria) this;
        }

        public Criteria andCompanytypeEqualTo(String value) {
            addCriterion("companyType =", value, "companytype");
            return (Criteria) this;
        }

        public Criteria andCompanytypeNotEqualTo(String value) {
            addCriterion("companyType <>", value, "companytype");
            return (Criteria) this;
        }

        public Criteria andCompanytypeGreaterThan(String value) {
            addCriterion("companyType >", value, "companytype");
            return (Criteria) this;
        }

        public Criteria andCompanytypeGreaterThanOrEqualTo(String value) {
            addCriterion("companyType >=", value, "companytype");
            return (Criteria) this;
        }

        public Criteria andCompanytypeLessThan(String value) {
            addCriterion("companyType <", value, "companytype");
            return (Criteria) this;
        }

        public Criteria andCompanytypeLessThanOrEqualTo(String value) {
            addCriterion("companyType <=", value, "companytype");
            return (Criteria) this;
        }

        public Criteria andCompanytypeLike(String value) {
            addCriterion("companyType like", value, "companytype");
            return (Criteria) this;
        }

        public Criteria andCompanytypeNotLike(String value) {
            addCriterion("companyType not like", value, "companytype");
            return (Criteria) this;
        }

        public Criteria andCompanytypeIn(List<String> values) {
            addCriterion("companyType in", values, "companytype");
            return (Criteria) this;
        }

        public Criteria andCompanytypeNotIn(List<String> values) {
            addCriterion("companyType not in", values, "companytype");
            return (Criteria) this;
        }

        public Criteria andCompanytypeBetween(String value1, String value2) {
            addCriterion("companyType between", value1, value2, "companytype");
            return (Criteria) this;
        }

        public Criteria andCompanytypeNotBetween(String value1, String value2) {
            addCriterion("companyType not between", value1, value2, "companytype");
            return (Criteria) this;
        }

        public Criteria andRegisteredassetsIsNull() {
            addCriterion("registeredAssets is null");
            return (Criteria) this;
        }

        public Criteria andRegisteredassetsIsNotNull() {
            addCriterion("registeredAssets is not null");
            return (Criteria) this;
        }

        public Criteria andRegisteredassetsEqualTo(String value) {
            addCriterion("registeredAssets =", value, "registeredassets");
            return (Criteria) this;
        }

        public Criteria andRegisteredassetsNotEqualTo(String value) {
            addCriterion("registeredAssets <>", value, "registeredassets");
            return (Criteria) this;
        }

        public Criteria andRegisteredassetsGreaterThan(String value) {
            addCriterion("registeredAssets >", value, "registeredassets");
            return (Criteria) this;
        }

        public Criteria andRegisteredassetsGreaterThanOrEqualTo(String value) {
            addCriterion("registeredAssets >=", value, "registeredassets");
            return (Criteria) this;
        }

        public Criteria andRegisteredassetsLessThan(String value) {
            addCriterion("registeredAssets <", value, "registeredassets");
            return (Criteria) this;
        }

        public Criteria andRegisteredassetsLessThanOrEqualTo(String value) {
            addCriterion("registeredAssets <=", value, "registeredassets");
            return (Criteria) this;
        }

        public Criteria andRegisteredassetsLike(String value) {
            addCriterion("registeredAssets like", value, "registeredassets");
            return (Criteria) this;
        }

        public Criteria andRegisteredassetsNotLike(String value) {
            addCriterion("registeredAssets not like", value, "registeredassets");
            return (Criteria) this;
        }

        public Criteria andRegisteredassetsIn(List<String> values) {
            addCriterion("registeredAssets in", values, "registeredassets");
            return (Criteria) this;
        }

        public Criteria andRegisteredassetsNotIn(List<String> values) {
            addCriterion("registeredAssets not in", values, "registeredassets");
            return (Criteria) this;
        }

        public Criteria andRegisteredassetsBetween(String value1, String value2) {
            addCriterion("registeredAssets between", value1, value2, "registeredassets");
            return (Criteria) this;
        }

        public Criteria andRegisteredassetsNotBetween(String value1, String value2) {
            addCriterion("registeredAssets not between", value1, value2, "registeredassets");
            return (Criteria) this;
        }

        public Criteria andEstablishmentdateIsNull() {
            addCriterion("establishmentDate is null");
            return (Criteria) this;
        }

        public Criteria andEstablishmentdateIsNotNull() {
            addCriterion("establishmentDate is not null");
            return (Criteria) this;
        }

        public Criteria andEstablishmentdateEqualTo(String value) {
            addCriterion("establishmentDate =", value, "establishmentdate");
            return (Criteria) this;
        }

        public Criteria andEstablishmentdateNotEqualTo(String value) {
            addCriterion("establishmentDate <>", value, "establishmentdate");
            return (Criteria) this;
        }

        public Criteria andEstablishmentdateGreaterThan(String value) {
            addCriterion("establishmentDate >", value, "establishmentdate");
            return (Criteria) this;
        }

        public Criteria andEstablishmentdateGreaterThanOrEqualTo(String value) {
            addCriterion("establishmentDate >=", value, "establishmentdate");
            return (Criteria) this;
        }

        public Criteria andEstablishmentdateLessThan(String value) {
            addCriterion("establishmentDate <", value, "establishmentdate");
            return (Criteria) this;
        }

        public Criteria andEstablishmentdateLessThanOrEqualTo(String value) {
            addCriterion("establishmentDate <=", value, "establishmentdate");
            return (Criteria) this;
        }

        public Criteria andEstablishmentdateLike(String value) {
            addCriterion("establishmentDate like", value, "establishmentdate");
            return (Criteria) this;
        }

        public Criteria andEstablishmentdateNotLike(String value) {
            addCriterion("establishmentDate not like", value, "establishmentdate");
            return (Criteria) this;
        }

        public Criteria andEstablishmentdateIn(List<String> values) {
            addCriterion("establishmentDate in", values, "establishmentdate");
            return (Criteria) this;
        }

        public Criteria andEstablishmentdateNotIn(List<String> values) {
            addCriterion("establishmentDate not in", values, "establishmentdate");
            return (Criteria) this;
        }

        public Criteria andEstablishmentdateBetween(String value1, String value2) {
            addCriterion("establishmentDate between", value1, value2, "establishmentdate");
            return (Criteria) this;
        }

        public Criteria andEstablishmentdateNotBetween(String value1, String value2) {
            addCriterion("establishmentDate not between", value1, value2, "establishmentdate");
            return (Criteria) this;
        }

        public Criteria andBeginoperatingperiodIsNull() {
            addCriterion("beginOperatingPeriod is null");
            return (Criteria) this;
        }

        public Criteria andBeginoperatingperiodIsNotNull() {
            addCriterion("beginOperatingPeriod is not null");
            return (Criteria) this;
        }

        public Criteria andBeginoperatingperiodEqualTo(String value) {
            addCriterion("beginOperatingPeriod =", value, "beginoperatingperiod");
            return (Criteria) this;
        }

        public Criteria andBeginoperatingperiodNotEqualTo(String value) {
            addCriterion("beginOperatingPeriod <>", value, "beginoperatingperiod");
            return (Criteria) this;
        }

        public Criteria andBeginoperatingperiodGreaterThan(String value) {
            addCriterion("beginOperatingPeriod >", value, "beginoperatingperiod");
            return (Criteria) this;
        }

        public Criteria andBeginoperatingperiodGreaterThanOrEqualTo(String value) {
            addCriterion("beginOperatingPeriod >=", value, "beginoperatingperiod");
            return (Criteria) this;
        }

        public Criteria andBeginoperatingperiodLessThan(String value) {
            addCriterion("beginOperatingPeriod <", value, "beginoperatingperiod");
            return (Criteria) this;
        }

        public Criteria andBeginoperatingperiodLessThanOrEqualTo(String value) {
            addCriterion("beginOperatingPeriod <=", value, "beginoperatingperiod");
            return (Criteria) this;
        }

        public Criteria andBeginoperatingperiodLike(String value) {
            addCriterion("beginOperatingPeriod like", value, "beginoperatingperiod");
            return (Criteria) this;
        }

        public Criteria andBeginoperatingperiodNotLike(String value) {
            addCriterion("beginOperatingPeriod not like", value, "beginoperatingperiod");
            return (Criteria) this;
        }

        public Criteria andBeginoperatingperiodIn(List<String> values) {
            addCriterion("beginOperatingPeriod in", values, "beginoperatingperiod");
            return (Criteria) this;
        }

        public Criteria andBeginoperatingperiodNotIn(List<String> values) {
            addCriterion("beginOperatingPeriod not in", values, "beginoperatingperiod");
            return (Criteria) this;
        }

        public Criteria andBeginoperatingperiodBetween(String value1, String value2) {
            addCriterion("beginOperatingPeriod between", value1, value2, "beginoperatingperiod");
            return (Criteria) this;
        }

        public Criteria andBeginoperatingperiodNotBetween(String value1, String value2) {
            addCriterion("beginOperatingPeriod not between", value1, value2, "beginoperatingperiod");
            return (Criteria) this;
        }

        public Criteria andEndoperatingperiodIsNull() {
            addCriterion("endOperatingPeriod is null");
            return (Criteria) this;
        }

        public Criteria andEndoperatingperiodIsNotNull() {
            addCriterion("endOperatingPeriod is not null");
            return (Criteria) this;
        }

        public Criteria andEndoperatingperiodEqualTo(String value) {
            addCriterion("endOperatingPeriod =", value, "endoperatingperiod");
            return (Criteria) this;
        }

        public Criteria andEndoperatingperiodNotEqualTo(String value) {
            addCriterion("endOperatingPeriod <>", value, "endoperatingperiod");
            return (Criteria) this;
        }

        public Criteria andEndoperatingperiodGreaterThan(String value) {
            addCriterion("endOperatingPeriod >", value, "endoperatingperiod");
            return (Criteria) this;
        }

        public Criteria andEndoperatingperiodGreaterThanOrEqualTo(String value) {
            addCriterion("endOperatingPeriod >=", value, "endoperatingperiod");
            return (Criteria) this;
        }

        public Criteria andEndoperatingperiodLessThan(String value) {
            addCriterion("endOperatingPeriod <", value, "endoperatingperiod");
            return (Criteria) this;
        }

        public Criteria andEndoperatingperiodLessThanOrEqualTo(String value) {
            addCriterion("endOperatingPeriod <=", value, "endoperatingperiod");
            return (Criteria) this;
        }

        public Criteria andEndoperatingperiodLike(String value) {
            addCriterion("endOperatingPeriod like", value, "endoperatingperiod");
            return (Criteria) this;
        }

        public Criteria andEndoperatingperiodNotLike(String value) {
            addCriterion("endOperatingPeriod not like", value, "endoperatingperiod");
            return (Criteria) this;
        }

        public Criteria andEndoperatingperiodIn(List<String> values) {
            addCriterion("endOperatingPeriod in", values, "endoperatingperiod");
            return (Criteria) this;
        }

        public Criteria andEndoperatingperiodNotIn(List<String> values) {
            addCriterion("endOperatingPeriod not in", values, "endoperatingperiod");
            return (Criteria) this;
        }

        public Criteria andEndoperatingperiodBetween(String value1, String value2) {
            addCriterion("endOperatingPeriod between", value1, value2, "endoperatingperiod");
            return (Criteria) this;
        }

        public Criteria andEndoperatingperiodNotBetween(String value1, String value2) {
            addCriterion("endOperatingPeriod not between", value1, value2, "endoperatingperiod");
            return (Criteria) this;
        }

        public Criteria andRegistrationauthorityIsNull() {
            addCriterion("registrationAuthority is null");
            return (Criteria) this;
        }

        public Criteria andRegistrationauthorityIsNotNull() {
            addCriterion("registrationAuthority is not null");
            return (Criteria) this;
        }

        public Criteria andRegistrationauthorityEqualTo(String value) {
            addCriterion("registrationAuthority =", value, "registrationauthority");
            return (Criteria) this;
        }

        public Criteria andRegistrationauthorityNotEqualTo(String value) {
            addCriterion("registrationAuthority <>", value, "registrationauthority");
            return (Criteria) this;
        }

        public Criteria andRegistrationauthorityGreaterThan(String value) {
            addCriterion("registrationAuthority >", value, "registrationauthority");
            return (Criteria) this;
        }

        public Criteria andRegistrationauthorityGreaterThanOrEqualTo(String value) {
            addCriterion("registrationAuthority >=", value, "registrationauthority");
            return (Criteria) this;
        }

        public Criteria andRegistrationauthorityLessThan(String value) {
            addCriterion("registrationAuthority <", value, "registrationauthority");
            return (Criteria) this;
        }

        public Criteria andRegistrationauthorityLessThanOrEqualTo(String value) {
            addCriterion("registrationAuthority <=", value, "registrationauthority");
            return (Criteria) this;
        }

        public Criteria andRegistrationauthorityLike(String value) {
            addCriterion("registrationAuthority like", value, "registrationauthority");
            return (Criteria) this;
        }

        public Criteria andRegistrationauthorityNotLike(String value) {
            addCriterion("registrationAuthority not like", value, "registrationauthority");
            return (Criteria) this;
        }

        public Criteria andRegistrationauthorityIn(List<String> values) {
            addCriterion("registrationAuthority in", values, "registrationauthority");
            return (Criteria) this;
        }

        public Criteria andRegistrationauthorityNotIn(List<String> values) {
            addCriterion("registrationAuthority not in", values, "registrationauthority");
            return (Criteria) this;
        }

        public Criteria andRegistrationauthorityBetween(String value1, String value2) {
            addCriterion("registrationAuthority between", value1, value2, "registrationauthority");
            return (Criteria) this;
        }

        public Criteria andRegistrationauthorityNotBetween(String value1, String value2) {
            addCriterion("registrationAuthority not between", value1, value2, "registrationauthority");
            return (Criteria) this;
        }

        public Criteria andApproveddateIsNull() {
            addCriterion("approvedDate is null");
            return (Criteria) this;
        }

        public Criteria andApproveddateIsNotNull() {
            addCriterion("approvedDate is not null");
            return (Criteria) this;
        }

        public Criteria andApproveddateEqualTo(String value) {
            addCriterion("approvedDate =", value, "approveddate");
            return (Criteria) this;
        }

        public Criteria andApproveddateNotEqualTo(String value) {
            addCriterion("approvedDate <>", value, "approveddate");
            return (Criteria) this;
        }

        public Criteria andApproveddateGreaterThan(String value) {
            addCriterion("approvedDate >", value, "approveddate");
            return (Criteria) this;
        }

        public Criteria andApproveddateGreaterThanOrEqualTo(String value) {
            addCriterion("approvedDate >=", value, "approveddate");
            return (Criteria) this;
        }

        public Criteria andApproveddateLessThan(String value) {
            addCriterion("approvedDate <", value, "approveddate");
            return (Criteria) this;
        }

        public Criteria andApproveddateLessThanOrEqualTo(String value) {
            addCriterion("approvedDate <=", value, "approveddate");
            return (Criteria) this;
        }

        public Criteria andApproveddateLike(String value) {
            addCriterion("approvedDate like", value, "approveddate");
            return (Criteria) this;
        }

        public Criteria andApproveddateNotLike(String value) {
            addCriterion("approvedDate not like", value, "approveddate");
            return (Criteria) this;
        }

        public Criteria andApproveddateIn(List<String> values) {
            addCriterion("approvedDate in", values, "approveddate");
            return (Criteria) this;
        }

        public Criteria andApproveddateNotIn(List<String> values) {
            addCriterion("approvedDate not in", values, "approveddate");
            return (Criteria) this;
        }

        public Criteria andApproveddateBetween(String value1, String value2) {
            addCriterion("approvedDate between", value1, value2, "approveddate");
            return (Criteria) this;
        }

        public Criteria andApproveddateNotBetween(String value1, String value2) {
            addCriterion("approvedDate not between", value1, value2, "approveddate");
            return (Criteria) this;
        }

        public Criteria andRegisterstateIsNull() {
            addCriterion("registerState is null");
            return (Criteria) this;
        }

        public Criteria andRegisterstateIsNotNull() {
            addCriterion("registerState is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterstateEqualTo(String value) {
            addCriterion("registerState =", value, "registerstate");
            return (Criteria) this;
        }

        public Criteria andRegisterstateNotEqualTo(String value) {
            addCriterion("registerState <>", value, "registerstate");
            return (Criteria) this;
        }

        public Criteria andRegisterstateGreaterThan(String value) {
            addCriterion("registerState >", value, "registerstate");
            return (Criteria) this;
        }

        public Criteria andRegisterstateGreaterThanOrEqualTo(String value) {
            addCriterion("registerState >=", value, "registerstate");
            return (Criteria) this;
        }

        public Criteria andRegisterstateLessThan(String value) {
            addCriterion("registerState <", value, "registerstate");
            return (Criteria) this;
        }

        public Criteria andRegisterstateLessThanOrEqualTo(String value) {
            addCriterion("registerState <=", value, "registerstate");
            return (Criteria) this;
        }

        public Criteria andRegisterstateLike(String value) {
            addCriterion("registerState like", value, "registerstate");
            return (Criteria) this;
        }

        public Criteria andRegisterstateNotLike(String value) {
            addCriterion("registerState not like", value, "registerstate");
            return (Criteria) this;
        }

        public Criteria andRegisterstateIn(List<String> values) {
            addCriterion("registerState in", values, "registerstate");
            return (Criteria) this;
        }

        public Criteria andRegisterstateNotIn(List<String> values) {
            addCriterion("registerState not in", values, "registerstate");
            return (Criteria) this;
        }

        public Criteria andRegisterstateBetween(String value1, String value2) {
            addCriterion("registerState between", value1, value2, "registerstate");
            return (Criteria) this;
        }

        public Criteria andRegisterstateNotBetween(String value1, String value2) {
            addCriterion("registerState not between", value1, value2, "registerstate");
            return (Criteria) this;
        }

        public Criteria andResidenceIsNull() {
            addCriterion("residence is null");
            return (Criteria) this;
        }

        public Criteria andResidenceIsNotNull() {
            addCriterion("residence is not null");
            return (Criteria) this;
        }

        public Criteria andResidenceEqualTo(String value) {
            addCriterion("residence =", value, "residence");
            return (Criteria) this;
        }

        public Criteria andResidenceNotEqualTo(String value) {
            addCriterion("residence <>", value, "residence");
            return (Criteria) this;
        }

        public Criteria andResidenceGreaterThan(String value) {
            addCriterion("residence >", value, "residence");
            return (Criteria) this;
        }

        public Criteria andResidenceGreaterThanOrEqualTo(String value) {
            addCriterion("residence >=", value, "residence");
            return (Criteria) this;
        }

        public Criteria andResidenceLessThan(String value) {
            addCriterion("residence <", value, "residence");
            return (Criteria) this;
        }

        public Criteria andResidenceLessThanOrEqualTo(String value) {
            addCriterion("residence <=", value, "residence");
            return (Criteria) this;
        }

        public Criteria andResidenceLike(String value) {
            addCriterion("residence like", value, "residence");
            return (Criteria) this;
        }

        public Criteria andResidenceNotLike(String value) {
            addCriterion("residence not like", value, "residence");
            return (Criteria) this;
        }

        public Criteria andResidenceIn(List<String> values) {
            addCriterion("residence in", values, "residence");
            return (Criteria) this;
        }

        public Criteria andResidenceNotIn(List<String> values) {
            addCriterion("residence not in", values, "residence");
            return (Criteria) this;
        }

        public Criteria andResidenceBetween(String value1, String value2) {
            addCriterion("residence between", value1, value2, "residence");
            return (Criteria) this;
        }

        public Criteria andResidenceNotBetween(String value1, String value2) {
            addCriterion("residence not between", value1, value2, "residence");
            return (Criteria) this;
        }

        public Criteria andBusinessscopeIsNull() {
            addCriterion("businessScope is null");
            return (Criteria) this;
        }

        public Criteria andBusinessscopeIsNotNull() {
            addCriterion("businessScope is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessscopeEqualTo(String value) {
            addCriterion("businessScope =", value, "businessscope");
            return (Criteria) this;
        }

        public Criteria andBusinessscopeNotEqualTo(String value) {
            addCriterion("businessScope <>", value, "businessscope");
            return (Criteria) this;
        }

        public Criteria andBusinessscopeGreaterThan(String value) {
            addCriterion("businessScope >", value, "businessscope");
            return (Criteria) this;
        }

        public Criteria andBusinessscopeGreaterThanOrEqualTo(String value) {
            addCriterion("businessScope >=", value, "businessscope");
            return (Criteria) this;
        }

        public Criteria andBusinessscopeLessThan(String value) {
            addCriterion("businessScope <", value, "businessscope");
            return (Criteria) this;
        }

        public Criteria andBusinessscopeLessThanOrEqualTo(String value) {
            addCriterion("businessScope <=", value, "businessscope");
            return (Criteria) this;
        }

        public Criteria andBusinessscopeLike(String value) {
            addCriterion("businessScope like", value, "businessscope");
            return (Criteria) this;
        }

        public Criteria andBusinessscopeNotLike(String value) {
            addCriterion("businessScope not like", value, "businessscope");
            return (Criteria) this;
        }

        public Criteria andBusinessscopeIn(List<String> values) {
            addCriterion("businessScope in", values, "businessscope");
            return (Criteria) this;
        }

        public Criteria andBusinessscopeNotIn(List<String> values) {
            addCriterion("businessScope not in", values, "businessscope");
            return (Criteria) this;
        }

        public Criteria andBusinessscopeBetween(String value1, String value2) {
            addCriterion("businessScope between", value1, value2, "businessscope");
            return (Criteria) this;
        }

        public Criteria andBusinessscopeNotBetween(String value1, String value2) {
            addCriterion("businessScope not between", value1, value2, "businessscope");
            return (Criteria) this;
        }

        public Criteria andCompanymanagerIsNull() {
            addCriterion("companymanager is null");
            return (Criteria) this;
        }

        public Criteria andCompanymanagerIsNotNull() {
            addCriterion("companymanager is not null");
            return (Criteria) this;
        }

        public Criteria andCompanymanagerEqualTo(String value) {
            addCriterion("companymanager =", value, "companymanager");
            return (Criteria) this;
        }

        public Criteria andCompanymanagerNotEqualTo(String value) {
            addCriterion("companymanager <>", value, "companymanager");
            return (Criteria) this;
        }

        public Criteria andCompanymanagerGreaterThan(String value) {
            addCriterion("companymanager >", value, "companymanager");
            return (Criteria) this;
        }

        public Criteria andCompanymanagerGreaterThanOrEqualTo(String value) {
            addCriterion("companymanager >=", value, "companymanager");
            return (Criteria) this;
        }

        public Criteria andCompanymanagerLessThan(String value) {
            addCriterion("companymanager <", value, "companymanager");
            return (Criteria) this;
        }

        public Criteria andCompanymanagerLessThanOrEqualTo(String value) {
            addCriterion("companymanager <=", value, "companymanager");
            return (Criteria) this;
        }

        public Criteria andCompanymanagerLike(String value) {
            addCriterion("companymanager like", value, "companymanager");
            return (Criteria) this;
        }

        public Criteria andCompanymanagerNotLike(String value) {
            addCriterion("companymanager not like", value, "companymanager");
            return (Criteria) this;
        }

        public Criteria andCompanymanagerIn(List<String> values) {
            addCriterion("companymanager in", values, "companymanager");
            return (Criteria) this;
        }

        public Criteria andCompanymanagerNotIn(List<String> values) {
            addCriterion("companymanager not in", values, "companymanager");
            return (Criteria) this;
        }

        public Criteria andCompanymanagerBetween(String value1, String value2) {
            addCriterion("companymanager between", value1, value2, "companymanager");
            return (Criteria) this;
        }

        public Criteria andCompanymanagerNotBetween(String value1, String value2) {
            addCriterion("companymanager not between", value1, value2, "companymanager");
            return (Criteria) this;
        }

        public Criteria andIcCodeIsNull() {
            addCriterion("IC_CODE is null");
            return (Criteria) this;
        }

        public Criteria andIcCodeIsNotNull() {
            addCriterion("IC_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andIcCodeEqualTo(String value) {
            addCriterion("IC_CODE =", value, "icCode");
            return (Criteria) this;
        }

        public Criteria andIcCodeNotEqualTo(String value) {
            addCriterion("IC_CODE <>", value, "icCode");
            return (Criteria) this;
        }

        public Criteria andIcCodeGreaterThan(String value) {
            addCriterion("IC_CODE >", value, "icCode");
            return (Criteria) this;
        }

        public Criteria andIcCodeGreaterThanOrEqualTo(String value) {
            addCriterion("IC_CODE >=", value, "icCode");
            return (Criteria) this;
        }

        public Criteria andIcCodeLessThan(String value) {
            addCriterion("IC_CODE <", value, "icCode");
            return (Criteria) this;
        }

        public Criteria andIcCodeLessThanOrEqualTo(String value) {
            addCriterion("IC_CODE <=", value, "icCode");
            return (Criteria) this;
        }

        public Criteria andIcCodeLike(String value) {
            addCriterion("IC_CODE like", value, "icCode");
            return (Criteria) this;
        }

        public Criteria andIcCodeNotLike(String value) {
            addCriterion("IC_CODE not like", value, "icCode");
            return (Criteria) this;
        }

        public Criteria andIcCodeIn(List<String> values) {
            addCriterion("IC_CODE in", values, "icCode");
            return (Criteria) this;
        }

        public Criteria andIcCodeNotIn(List<String> values) {
            addCriterion("IC_CODE not in", values, "icCode");
            return (Criteria) this;
        }

        public Criteria andIcCodeBetween(String value1, String value2) {
            addCriterion("IC_CODE between", value1, value2, "icCode");
            return (Criteria) this;
        }

        public Criteria andIcCodeNotBetween(String value1, String value2) {
            addCriterion("IC_CODE not between", value1, value2, "icCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table companydetail
     *
     * @mbg.generated do_not_delete_during_merge Mon Nov 13 15:22:44 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table companydetail
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}