package com.echarts.pojo;

import java.util.Date;

public class ComPanyDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companydetail.id
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companydetail.user_id
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companydetail.companyName
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    private String companyname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companydetail.companyLicence
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    private String companylicence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companydetail.registrarName
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    private String registrarname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companydetail.registrarPhone
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    private String registrarphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companydetail.incorporatorName
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    private String incorporatorname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companydetail.companyState
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    private Byte companystate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companydetail.auditTime
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    private Date audittime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companydetail.registerTime
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    private Date registertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companydetail.loanState
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    private Byte loanstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companydetail.companyType
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    private String companytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companydetail.registeredAssets
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    private String registeredassets;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companydetail.establishmentDate
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    private String establishmentdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companydetail.beginOperatingPeriod
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    private String beginoperatingperiod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companydetail.endOperatingPeriod
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    private String endoperatingperiod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companydetail.registrationAuthority
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    private String registrationauthority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companydetail.approvedDate
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    private String approveddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companydetail.registerState
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    private String registerstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companydetail.residence
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    private String residence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companydetail.businessScope
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    private String businessscope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companydetail.companymanager
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    private String companymanager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companydetail.IC_CODE
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    private String icCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companydetail.id
     *
     * @return the value of companydetail.id
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companydetail.id
     *
     * @param id the value for companydetail.id
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companydetail.user_id
     *
     * @return the value of companydetail.user_id
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companydetail.user_id
     *
     * @param userId the value for companydetail.user_id
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companydetail.companyName
     *
     * @return the value of companydetail.companyName
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companydetail.companyName
     *
     * @param companyname the value for companydetail.companyName
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname == null ? null : companyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companydetail.companyLicence
     *
     * @return the value of companydetail.companyLicence
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public String getCompanylicence() {
        return companylicence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companydetail.companyLicence
     *
     * @param companylicence the value for companydetail.companyLicence
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public void setCompanylicence(String companylicence) {
        this.companylicence = companylicence == null ? null : companylicence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companydetail.registrarName
     *
     * @return the value of companydetail.registrarName
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public String getRegistrarname() {
        return registrarname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companydetail.registrarName
     *
     * @param registrarname the value for companydetail.registrarName
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public void setRegistrarname(String registrarname) {
        this.registrarname = registrarname == null ? null : registrarname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companydetail.registrarPhone
     *
     * @return the value of companydetail.registrarPhone
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public String getRegistrarphone() {
        return registrarphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companydetail.registrarPhone
     *
     * @param registrarphone the value for companydetail.registrarPhone
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public void setRegistrarphone(String registrarphone) {
        this.registrarphone = registrarphone == null ? null : registrarphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companydetail.incorporatorName
     *
     * @return the value of companydetail.incorporatorName
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public String getIncorporatorname() {
        return incorporatorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companydetail.incorporatorName
     *
     * @param incorporatorname the value for companydetail.incorporatorName
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public void setIncorporatorname(String incorporatorname) {
        this.incorporatorname = incorporatorname == null ? null : incorporatorname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companydetail.companyState
     *
     * @return the value of companydetail.companyState
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public Byte getCompanystate() {
        return companystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companydetail.companyState
     *
     * @param companystate the value for companydetail.companyState
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public void setCompanystate(Byte companystate) {
        this.companystate = companystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companydetail.auditTime
     *
     * @return the value of companydetail.auditTime
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public Date getAudittime() {
        return audittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companydetail.auditTime
     *
     * @param audittime the value for companydetail.auditTime
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public void setAudittime(Date audittime) {
        this.audittime = audittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companydetail.registerTime
     *
     * @return the value of companydetail.registerTime
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public Date getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companydetail.registerTime
     *
     * @param registertime the value for companydetail.registerTime
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public void setRegistertime(Date registertime) {
        this.registertime = registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companydetail.loanState
     *
     * @return the value of companydetail.loanState
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public Byte getLoanstate() {
        return loanstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companydetail.loanState
     *
     * @param loanstate the value for companydetail.loanState
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public void setLoanstate(Byte loanstate) {
        this.loanstate = loanstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companydetail.companyType
     *
     * @return the value of companydetail.companyType
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public String getCompanytype() {
        return companytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companydetail.companyType
     *
     * @param companytype the value for companydetail.companyType
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public void setCompanytype(String companytype) {
        this.companytype = companytype == null ? null : companytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companydetail.registeredAssets
     *
     * @return the value of companydetail.registeredAssets
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public String getRegisteredassets() {
        return registeredassets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companydetail.registeredAssets
     *
     * @param registeredassets the value for companydetail.registeredAssets
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public void setRegisteredassets(String registeredassets) {
        this.registeredassets = registeredassets == null ? null : registeredassets.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companydetail.establishmentDate
     *
     * @return the value of companydetail.establishmentDate
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public String getEstablishmentdate() {
        return establishmentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companydetail.establishmentDate
     *
     * @param establishmentdate the value for companydetail.establishmentDate
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public void setEstablishmentdate(String establishmentdate) {
        this.establishmentdate = establishmentdate == null ? null : establishmentdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companydetail.beginOperatingPeriod
     *
     * @return the value of companydetail.beginOperatingPeriod
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public String getBeginoperatingperiod() {
        return beginoperatingperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companydetail.beginOperatingPeriod
     *
     * @param beginoperatingperiod the value for companydetail.beginOperatingPeriod
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public void setBeginoperatingperiod(String beginoperatingperiod) {
        this.beginoperatingperiod = beginoperatingperiod == null ? null : beginoperatingperiod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companydetail.endOperatingPeriod
     *
     * @return the value of companydetail.endOperatingPeriod
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public String getEndoperatingperiod() {
        return endoperatingperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companydetail.endOperatingPeriod
     *
     * @param endoperatingperiod the value for companydetail.endOperatingPeriod
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public void setEndoperatingperiod(String endoperatingperiod) {
        this.endoperatingperiod = endoperatingperiod == null ? null : endoperatingperiod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companydetail.registrationAuthority
     *
     * @return the value of companydetail.registrationAuthority
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public String getRegistrationauthority() {
        return registrationauthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companydetail.registrationAuthority
     *
     * @param registrationauthority the value for companydetail.registrationAuthority
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public void setRegistrationauthority(String registrationauthority) {
        this.registrationauthority = registrationauthority == null ? null : registrationauthority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companydetail.approvedDate
     *
     * @return the value of companydetail.approvedDate
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public String getApproveddate() {
        return approveddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companydetail.approvedDate
     *
     * @param approveddate the value for companydetail.approvedDate
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public void setApproveddate(String approveddate) {
        this.approveddate = approveddate == null ? null : approveddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companydetail.registerState
     *
     * @return the value of companydetail.registerState
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public String getRegisterstate() {
        return registerstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companydetail.registerState
     *
     * @param registerstate the value for companydetail.registerState
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public void setRegisterstate(String registerstate) {
        this.registerstate = registerstate == null ? null : registerstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companydetail.residence
     *
     * @return the value of companydetail.residence
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public String getResidence() {
        return residence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companydetail.residence
     *
     * @param residence the value for companydetail.residence
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public void setResidence(String residence) {
        this.residence = residence == null ? null : residence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companydetail.businessScope
     *
     * @return the value of companydetail.businessScope
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public String getBusinessscope() {
        return businessscope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companydetail.businessScope
     *
     * @param businessscope the value for companydetail.businessScope
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public void setBusinessscope(String businessscope) {
        this.businessscope = businessscope == null ? null : businessscope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companydetail.companymanager
     *
     * @return the value of companydetail.companymanager
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public String getCompanymanager() {
        return companymanager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companydetail.companymanager
     *
     * @param companymanager the value for companydetail.companymanager
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public void setCompanymanager(String companymanager) {
        this.companymanager = companymanager == null ? null : companymanager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companydetail.IC_CODE
     *
     * @return the value of companydetail.IC_CODE
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public String getIcCode() {
        return icCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companydetail.IC_CODE
     *
     * @param icCode the value for companydetail.IC_CODE
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    public void setIcCode(String icCode) {
        this.icCode = icCode == null ? null : icCode.trim();
    }
}