package com.echarts.mapper;

import com.echarts.pojo.CdfTotal;
import com.echarts.pojo.CdfTotalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CdfTotalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdf_total
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    long countByExample(CdfTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdf_total
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    int deleteByExample(CdfTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdf_total
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    int deleteByPrimaryKey(Integer totalid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdf_total
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    int insert(CdfTotal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdf_total
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    int insertSelective(CdfTotal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdf_total
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    List<CdfTotal> selectByExample(CdfTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdf_total
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    CdfTotal selectByPrimaryKey(Integer totalid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdf_total
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    int updateByExampleSelective(@Param("record") CdfTotal record, @Param("example") CdfTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdf_total
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    int updateByExample(@Param("record") CdfTotal record, @Param("example") CdfTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdf_total
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    int updateByPrimaryKeySelective(CdfTotal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdf_total
     *
     * @mbg.generated Mon Nov 13 15:22:44 CST 2017
     */
    int updateByPrimaryKey(CdfTotal record);
}